name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            sudo snap install zig --classic --edge
            zig version
      - name: non-blocking test
        run: zig build test -Dforce_blocking=false
      - name: blocking test
        run: zig build test -Dforce_blocking=true
      - name: build server x86-linux-gnu
        run: cd support/autobahn/server && zig build -Dtarget=x86-linux-gnu
      - name: build server x86_64-linux-gnu
        run: cd support/autobahn/server && zig build -Dtarget=x86_64-linux-gnu
      - name: build server x86_64-windows-gnu
        run: cd support/autobahn/server && zig build -Dtarget=x86_64-windows-gnu
      - name: build client x86-linux-gnu
        run: cd support/autobahn/client && zig build -Dtarget=x86-linux-gnu
      - name: build server x86_64-linux-gnu
        run: cd support/autobahn/client && zig build -Dtarget=x86_64-linux-gnu
      - name: build clietn x86_64-windows-gnu
        run: cd support/autobahn/client && zig build -Dtarget=x86_64-windows-gnu
